name: Running Tests

on: [push]

permissions:
  checks: write

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: mypass
          POSTGRES_USER: myuser
          POSTGRES_DB: example

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - run: |
          sudo apt-get update && sudo apt-get install --yes --no-install-recommends postgresql-client
      - run: |
          psql -h localhost -U myuser -d example -c 'create table categories (id bigserial primary key, avatar varchar not null, title varchar not null);'
        env:
          PGPASSWORD: mypass
      - uses: actions/checkout@v4
      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Build with Maven
        run: mvn test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: '**/target/surefire-reports/TEST-*.xml'
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Set up Node.js 14.x
#        uses: actions/setup-node@v1
#        with:
#          node-version: 14.x
#
#      - name: Install dependencies
#        run: npm install
#
#      - name: migrate database
#        run: node migrate.js
#        env:
#          DBURL: "postgres://postgres:postgres@localhost:5432/postgres"
#
#      - name: Run the mock tests function
#        run: node getuser.js
#        env:
#          DBURL: postgres://postgres:postgres@localhost:5432/postgres
